steps:
  - name: "asia-south1-docker.pkg.dev/upheld-quasar-473307-h1/testing-repo/fast-api"
    id: "Run Migrations"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        set -e
        set -o pipefail

        echo "Installing cloud-sql-proxy and netcat..."
        apk add --no-cache wget netcat-openbsd
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy
        chmod +x /usr/local/bin/cloud_sql_proxy

        echo "Starting Cloud SQL Proxy in background..."
        /usr/local/bin/cloud_sql_proxy -instances=upheld-quasar-473307-h1:asia-south1:father-of-all-databases=tcp:5432 > /tmp/cloud_sql_proxy.log 2>&1 &
        PROXY_PID=$$!

        sleep 5

        echo "Cloud SQL Proxy started with PID: $$PROXY_PID"
        cat /tmp/cloud_sql_proxy.log

        export DB_HOST=127.0.0.1
        export DB_PORT=5432
        export DB_DATABASE=${_DB_DATABASE}
        export DB_USER=${_DB_USER}
        export DB_PASSWORD=${_DB_PASSWORD}

        # Navigate to the workspace directory (GCP Cloud Build automatically checks out code here)
        cd /workspace

        echo "Installing dependencies..."
        poetry install --no-interaction --no-ansi --no-root

        # Run database migrations
        echo "Running database migrations..."
        alembic upgrade head

        echo "Migrations completed successfully!"

        kill $$PROXY_PID || true

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 180s
