"""po_indexes

Revision ID: 2a8cc44e7136
Revises: 431f2f2f3bb8
Create Date: 2025-11-24 19:22:55.130064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8cc44e7136'
down_revision: Union[str, Sequence[str], None] = '431f2f2f3bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_purchase_orders_po_id_tenant_id', 'purchase_orders', ['po_id', 'tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_orders_po_id_tenant_id', table_name='purchase_orders')
    # ### end Alembic commands ###
