"""requisition_indexes

Revision ID: 431f2f2f3bb8
Revises: 5f75270bed04
Create Date: 2025-11-24 19:25:09.807124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431f2f2f3bb8'
down_revision: Union[str, Sequence[str], None] = '5f75270bed04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_requisitions_tenant_id_status', 'requisitions', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requisitions_tenant_id_status', table_name='requisitions')
    # ### end Alembic commands ###
