"""add indexing

Revision ID: 5f75270bed04
Revises: 7f58104d85ab
Create Date: 2025-11-24 17:11:42.680339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f75270bed04'
down_revision: Union[str, Sequence[str], None] = '7f58104d85ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email_tenant_id', 'users', ['email', 'tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_tenant_id', table_name='users')
    # ### end Alembic commands ###
