"""item_deleted_at

Revision ID: 6bdae2a6564f
Revises: 0ac9885734b7
Create Date: 2025-11-25 16:43:37.491881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdae2a6564f'
down_revision: Union[str, Sequence[str], None] = '0ac9885734b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'deleted_at')
    # ### end Alembic commands ###
