"""change_1

Revision ID: 81422c015a67
Revises: 2a8cc44e7136
Create Date: 2025-11-25 00:37:03.402844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81422c015a67'
down_revision: Union[str, Sequence[str], None] = '2a8cc44e7136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('test_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'test_column')
    # ### end Alembic commands ###
