"""remove_change_2

Revision ID: a902eef76856
Revises: c67e2a32e48b
Create Date: 2025-11-25 01:31:49.741139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a902eef76856'
down_revision: Union[str, Sequence[str], None] = 'c67e2a32e48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_col', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
