"""requisition_deleted

Revision ID: bc8fa73509a7
Revises: 3095dd1eec5b
Create Date: 2025-11-25 02:16:12.995339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8fa73509a7'
down_revision: Union[str, Sequence[str], None] = '3095dd1eec5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisitions', 'deleted_at')
    # ### end Alembic commands ###
