"""remove_change_1

Revision ID: c67e2a32e48b
Revises: aee0dad93075
Create Date: 2025-11-25 01:05:51.591129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67e2a32e48b'
down_revision: Union[str, Sequence[str], None] = 'aee0dad93075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'test_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('test_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
