"""11_test

Revision ID: c6bce05e68da
Revises: 82a154842afa
Create Date: 2025-11-25 14:46:51.210077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bce05e68da'
down_revision: Union[str, Sequence[str], None] = '82a154842afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('new_test_col', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'new_test_col')
    # ### end Alembic commands ###
